name: Unit tests
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - production

jobs:
  unittests:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"

      - name: test
        run: go test -v ./...
